//! Phase 8 (Block A, Tasks 1–2): KChat artifact-publishing bridge.
//!
//! Exposes the renderer-side "publish my export to a KChat
//! conversation" pipeline. The flow is:
//!
//! 1. Renderer calls one of the [`publish_*`] entry points with a
//!    conversation id and a typed [`KChatArtifactRequest`] (or
//!    [`KChatBrandKitArtifactRequest`] for `.kbrand`).
//! 2. The bridge drives [`crate::document`] to render the exported
//!    bytes (PNG / SVG / PDF / WebP / JPEG) **in memory** — no
//!    temp files are touched, so the renderer doesn't have to know
//!    about disk paths and a partially-published artifact never
//!    leaves debris behind. `.kbrand` uses the existing brand-kit
//!    archive serializer (also in-memory).
//! 3. A thumbnail is generated by reusing the existing
//!    [`crate::thumbnails`] pipeline (the same cache-aware renderer
//!    that drives the HomePage cover thumbnails), so we don't run
//!    a second renderer pass when the cover is already cached.
//! 4. The bytes + thumbnail + metadata are handed to
//!    [`kcreate_kchat_client::KChatBackendClient::publish_artifact`],
//!    which posts the multipart `POST /api/v1/conversations/{id}/artifacts`.
//!
//! Returns are typed wire-format mirrors of the REST response
//! shapes in [`kcreate_kchat_client::protocol`]. The TypeScript
//! side mirrors these as `KChatArtifactPublishResult` /
//! `KChatPublishedArtifact` in `apps/desktop/shared/scene.ts`.
//!
//! `kchat_backend_*` bridge functions live here rather than in
//! `kchat_backend.rs` because the artifact pipeline touches the
//! document/export tree, not the auth tree — keeping the modules
//! separate avoids growing `kchat_backend.rs` into a 1000-line
//! catch-all.

use base64::engine::general_purpose::STANDARD as BASE64_STANDARD;
use base64::Engine;
use kcreate_kchat_client::{
    ArtifactKind, ArtifactMetadata, ArtifactPublishParams, ArtifactPublishResult,
    ArtifactPublishThumbnail, ClientError, PublishedArtifact,
};
use serde::Deserialize;
use uuid::Uuid;

use crate::kchat_backend::KChatBackendBridgeError;

/// Maximum long-edge of the auto-generated thumbnail in pixels.
/// Matches the HomePage cover-thumbnail budget so a project that
/// already has a cached cover gets reused without a re-render.
const ARTIFACT_THUMBNAIL_MAX_DIM_PX: u32 = 512;

/// Bridge-facing request for [`kchat_backend_publish_artifact`].
///
/// Mirrored in `apps/desktop/shared/scene.ts` as
/// `KChatArtifactPublishRequest`. The renderer fills this in from
/// `ArtifactPublishPanel` (the format picker + preset chip + a
/// page selector when the user wants to scope the export).
///
/// Deserialise-only at the bridge boundary — the wire flow is
/// strictly renderer → bridge, so a `Serialize` impl would be
/// unused (and the wrapped export-request types only derive
/// `Deserialize` themselves).
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct KChatArtifactRequest {
    /// Wire format of the artifact to produce.
    pub kind: KChatArtifactRequestKind,
    /// Free-form export preset label echoed onto the rich-card
    /// chip. Optional — renderers that drove the export ad-hoc
    /// can omit it.
    #[serde(default)]
    pub export_preset: Option<String>,
    /// Page (artboard) name surfaced on the rich-card preview.
    /// The bridge does not look this up against the document graph
    /// — that's the renderer's job — so callers can pass any
    /// meaningful label (e.g. "Cover", "Mobile / 375 × 812").
    #[serde(default)]
    pub artboard_name: Option<String>,
}

/// Format-specific export configuration. Mirrored in
/// `scene.ts` as `KChatArtifactRequestKind` (a discriminated union
/// keyed on `format`).
#[derive(Debug, Clone, Deserialize)]
#[serde(tag = "format", rename_all = "camelCase")]
pub enum KChatArtifactRequestKind {
    /// Rasterised PNG export.
    Png(crate::document::PngExportRequest),
    /// Vector SVG export.
    Svg(KChatSvgArtifactRequest),
    /// PDF export.
    Pdf(crate::document::PdfExportRequest),
    /// Rasterised WebP export.
    Webp(crate::document::WebpExportRequest),
    /// JPEG fallback (opaque, photo-grade).
    Jpeg(crate::document::JpegExportRequest),
}

/// SVG export request as seen by the bridge. Wraps
/// [`kcreate_export::svg::SvgExportOptions`] alongside the optional
/// node-id filter so the renderer can publish "just this artboard"
/// without a separate scene snapshot.
#[derive(Debug, Clone, Default, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct KChatSvgArtifactRequest {
    #[serde(default)]
    pub options: kcreate_export::svg::SvgExportOptions,
    /// Optional node-id filter passed to
    /// [`kcreate_export::svg::export_svg_from_document`]. An empty
    /// vec means "the whole document", matching the bridge's
    /// [`crate::document::export_svg`] semantics.
    #[serde(default)]
    pub node_ids: Vec<Uuid>,
}

/// Bridge-facing request for [`kchat_backend_publish_brand_kit`].
/// Mirrored in `scene.ts` as `KChatBrandKitArtifactRequest`.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct KChatBrandKitArtifactRequest {
    /// Brand-kit to serialise. Must exist in the open project.
    pub brand_kit_id: Uuid,
    /// Free-form preset label (e.g. `"Brand Kit v3"`). Optional.
    #[serde(default)]
    pub export_preset: Option<String>,
}

/// Snapshot of the bytes + dimensions produced by an export step.
struct ExportArtifact {
    bytes: Vec<u8>,
    kind: ArtifactKind,
    /// Rasterised dimensions, when applicable. `None` for vector-
    /// only formats (SVG, PDF) and `.kbrand`.
    width_px: Option<u32>,
    height_px: Option<u32>,
}

/// Render the artifact to bytes per the requested kind, snapshot
/// the open project's id + name (so the metadata is stamped from
/// the same lock window the bytes were produced under), and post
/// the artifact + thumbnail + metadata to the KChat backend.
pub fn kchat_backend_publish_artifact(
    conversation_id: &str,
    request: KChatArtifactRequest,
) -> Result<ArtifactPublishResult, KChatBackendBridgeError> {
    let conversation_id = validate_conversation_id(conversation_id)?;
    // Fail fast on "no project open" / "not connected" BEFORE
    // doing any expensive render work. `project_identity` reads
    // the workspace slot under a single lock, so a torn read
    // between the identity snapshot and the render is impossible.
    let (project_id, project_name) = project_identity()?;
    crate::kchat_backend::require_client_for_artifacts()?;
    let export = render_artifact(&request.kind)?;
    let metadata = ArtifactMetadata {
        project_name,
        artboard_name: request.artboard_name,
        export_preset: request.export_preset,
        width_px: export.width_px,
        height_px: export.height_px,
        project_id,
        kind: export.kind,
    };
    let thumbnail = render_artifact_thumbnail();

    publish_with_client(conversation_id, export, thumbnail, metadata)
}

/// Serialise a brand kit (with its embedded font / logo asset
/// blobs) to a `.kbrand` archive and publish it as an artifact.
pub fn kchat_backend_publish_brand_kit(
    conversation_id: &str,
    request: KChatBrandKitArtifactRequest,
) -> Result<ArtifactPublishResult, KChatBackendBridgeError> {
    let conversation_id = validate_conversation_id(conversation_id)?;
    // Same fail-fast contract as `kchat_backend_publish_artifact`
    // — surface NoOpenProject / NotConnected before serialising
    // the kbrand archive (which would otherwise read the
    // workspace twice and waste the asset-snapshot work).
    let (project_id, project_name) = project_identity()?;
    crate::kchat_backend::require_client_for_artifacts()?;
    let (kit_name, bytes) =
        crate::document::brand_kit_export_to_bytes(request.brand_kit_id).map_err(bridge_error)?;
    let metadata = ArtifactMetadata {
        project_name,
        artboard_name: Some(kit_name),
        export_preset: request.export_preset,
        width_px: None,
        height_px: None,
        project_id,
        kind: ArtifactKind::BrandKit,
    };
    let thumbnail = render_artifact_thumbnail();
    let export = ExportArtifact {
        bytes,
        kind: ArtifactKind::BrandKit,
        width_px: None,
        height_px: None,
    };

    publish_with_client(conversation_id, export, thumbnail, metadata)
}

/// List previously-published artifacts for a conversation.
pub fn kchat_backend_list_artifacts(
    conversation_id: &str,
) -> Result<Vec<PublishedArtifact>, KChatBackendBridgeError> {
    let conversation_id = validate_conversation_id(conversation_id)?;
    let client = crate::kchat_backend::require_client_for_artifacts()?;
    let rt = crate::kchat_backend::runtime_for_artifacts()?;
    rt.block_on(client.list_artifacts(&conversation_id))
        .map_err(KChatBackendBridgeError::from)
}

fn publish_with_client(
    conversation_id: String,
    export: ExportArtifact,
    thumbnail: Option<ArtifactPublishThumbnail>,
    metadata: ArtifactMetadata,
) -> Result<ArtifactPublishResult, KChatBackendBridgeError> {
    let client = crate::kchat_backend::require_client_for_artifacts()?;
    let rt = crate::kchat_backend::runtime_for_artifacts()?;
    let params = ArtifactPublishParams {
        conversation_id,
        artifact_bytes: export.bytes,
        kind: export.kind,
        thumbnail,
        metadata,
    };
    rt.block_on(client.publish_artifact(params))
        .map_err(KChatBackendBridgeError::from)
}

fn render_artifact(
    kind: &KChatArtifactRequestKind,
) -> Result<ExportArtifact, KChatBackendBridgeError> {
    match kind {
        KChatArtifactRequestKind::Png(opts) => {
            let bytes = crate::document::export_png_bytes(opts).map_err(bridge_error)?;
            let (w, h) = scaled_dims(opts.width, opts.height, opts.scale);
            Ok(ExportArtifact {
                bytes,
                kind: ArtifactKind::Png,
                width_px: Some(w),
                height_px: Some(h),
            })
        }
        KChatArtifactRequestKind::Svg(req) => {
            let svg =
                crate::document::export_svg(&req.node_ids, &req.options).map_err(bridge_error)?;
            Ok(ExportArtifact {
                bytes: svg.into_bytes(),
                kind: ArtifactKind::Svg,
                width_px: None,
                height_px: None,
            })
        }
        KChatArtifactRequestKind::Pdf(opts) => {
            let bytes = crate::document::export_pdf_bytes(opts).map_err(bridge_error)?;
            Ok(ExportArtifact {
                bytes,
                kind: ArtifactKind::Pdf,
                width_px: None,
                height_px: None,
            })
        }
        KChatArtifactRequestKind::Webp(opts) => {
            let bytes = crate::document::export_webp_bytes(opts).map_err(bridge_error)?;
            let (w, h) = scaled_dims(opts.width, opts.height, opts.scale);
            Ok(ExportArtifact {
                bytes,
                kind: ArtifactKind::Webp,
                width_px: Some(w),
                height_px: Some(h),
            })
        }
        KChatArtifactRequestKind::Jpeg(opts) => {
            let bytes = crate::document::export_jpeg_bytes(opts).map_err(bridge_error)?;
            let (w, h) = scaled_dims(opts.width, opts.height, opts.scale);
            Ok(ExportArtifact {
                bytes,
                kind: ArtifactKind::Jpeg,
                width_px: Some(w),
                height_px: Some(h),
            })
        }
    }
}

/// Project id + project name pulled in a single workspace lock
/// window. Returns [`KChatBackendBridgeError::NoOpenProject`] when
/// no project is open.
fn project_identity() -> Result<(Uuid, String), KChatBackendBridgeError> {
    let info = crate::document::project_info().ok_or(KChatBackendBridgeError::NoOpenProject)?;
    Ok((info.id, info.name))
}

/// Render (or fetch from cache) the project's cover thumbnail as
/// PNG bytes + dimensions. Failures here are non-fatal: if the
/// renderer can't produce a thumbnail (no scene yet, GPU readback
/// failed, etc.) we publish with no thumbnail and the backend
/// falls back to its own preview pipeline. Logged via tracing so
/// operators can spot a pattern, but never blocks the publish.
fn render_artifact_thumbnail() -> Option<ArtifactPublishThumbnail> {
    match crate::thumbnails::ensure_cover_thumbnail(ARTIFACT_THUMBNAIL_MAX_DIM_PX) {
        Ok(t) => decode_thumbnail(t).ok(),
        Err(e) => {
            tracing::debug!(
                "kchat_artifact: cover thumbnail unavailable, publishing without thumbnail: {e}",
            );
            None
        }
    }
}

fn decode_thumbnail(
    t: crate::thumbnails::ThumbnailBytes,
) -> Result<ArtifactPublishThumbnail, KChatBackendBridgeError> {
    let bytes = BASE64_STANDARD.decode(&t.bytes_base64).map_err(|e| {
        KChatBackendBridgeError::Attestation(format!(
            "kchat_artifact: thumbnail base64 decode failed: {e}"
        ))
    })?;
    ArtifactPublishThumbnail::from_png(bytes, t.width, t.height).map_err(client_to_bridge)
}

fn validate_conversation_id(conversation_id: &str) -> Result<String, KChatBackendBridgeError> {
    if conversation_id.is_empty() {
        return Err(KChatBackendBridgeError::Attestation(
            "kchat_artifact: conversation_id must not be empty".to_string(),
        ));
    }
    Ok(conversation_id.to_string())
}

/// Final output dimensions = `floor(base * scale)`. Clamped to at
/// least 1 so the metadata never advertises a zero-pixel image.
/// Matches the post-scale dims `export_*` actually writes (see
/// `render_scene_to_png` in `thumbnails.rs` for the same math).
fn scaled_dims(width: u32, height: u32, scale: f32) -> (u32, u32) {
    let scale = if scale.is_finite() && scale > 0.0 {
        scale
    } else {
        1.0
    };
    let w = ((width as f32) * scale).round().max(1.0) as u32;
    let h = ((height as f32) * scale).round().max(1.0) as u32;
    (w, h)
}

fn bridge_error(e: crate::document::DocumentBridgeError) -> KChatBackendBridgeError {
    KChatBackendBridgeError::Attestation(format!("kchat_artifact: {e}"))
}

fn client_to_bridge(e: ClientError) -> KChatBackendBridgeError {
    KChatBackendBridgeError::Client(e)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scaled_dims_round_trip() {
        assert_eq!(scaled_dims(100, 50, 1.0), (100, 50));
        assert_eq!(scaled_dims(100, 50, 2.0), (200, 100));
        assert_eq!(scaled_dims(100, 50, 0.5), (50, 25));
    }

    #[test]
    fn scaled_dims_clamps_pathological_scale() {
        // Zero / NaN / negative scale should fall back to 1.0 so we
        // never advertise a 0×0 image in the metadata.
        assert_eq!(scaled_dims(100, 50, 0.0), (100, 50));
        assert_eq!(scaled_dims(100, 50, f32::NAN), (100, 50));
        assert_eq!(scaled_dims(100, 50, -1.0), (100, 50));
    }

    #[test]
    fn scaled_dims_clamps_to_at_least_one_pixel() {
        // A tiny base × tiny scale should still report ≥ 1 px so
        // the metadata is never `width: 0`.
        assert_eq!(scaled_dims(1, 1, 0.01), (1, 1));
    }

    #[test]
    fn validate_conversation_id_rejects_empty() {
        let err = validate_conversation_id("").unwrap_err();
        match err {
            KChatBackendBridgeError::Attestation(msg) => {
                assert!(msg.contains("conversation_id"), "msg was {msg}");
            }
            other => panic!("expected Attestation error, got {other:?}"),
        }
    }

    #[test]
    fn validate_conversation_id_passes_non_empty() {
        let id = validate_conversation_id("conv-123").unwrap();
        assert_eq!(id, "conv-123");
    }

    /// Pin the wire shape — the TS side mirrors the discriminated
    /// union as `{ format: "png", width, height, scale }` with the
    /// inner PNG fields flattened next to the discriminator. Serde
    /// must accept this against the inner `PngExportRequest` even
    /// though that struct carries `#[serde(deny_unknown_fields)]`.
    #[test]
    fn request_parses_png_with_flattened_format_tag() {
        let json = r#"{
            "kind": { "format": "png", "width": 1920, "height": 1080, "scale": 1.0 },
            "exportPreset": "PNG @1x",
            "artboardName": "Cover"
        }"#;
        let req: KChatArtifactRequest = serde_json::from_str(json).expect("png request parses");
        match req.kind {
            KChatArtifactRequestKind::Png(opts) => {
                assert_eq!(opts.width, 1920);
                assert_eq!(opts.height, 1080);
                assert!((opts.scale - 1.0).abs() < f32::EPSILON);
            }
            other => panic!("expected Png variant, got {other:?}"),
        }
        assert_eq!(req.export_preset.as_deref(), Some("PNG @1x"));
        assert_eq!(req.artboard_name.as_deref(), Some("Cover"));
    }

    #[test]
    fn request_parses_svg_with_node_filter() {
        let json = r#"{
            "kind": {
                "format": "svg",
                "options": { "width": 0, "height": 0, "includeMetadata": false, "optimize": true },
                "nodeIds": []
            }
        }"#;
        let req: KChatArtifactRequest = serde_json::from_str(json).expect("svg request parses");
        match req.kind {
            KChatArtifactRequestKind::Svg(svg_req) => {
                assert!(svg_req.options.optimize);
                assert!(svg_req.node_ids.is_empty());
            }
            other => panic!("expected Svg variant, got {other:?}"),
        }
    }

    #[test]
    fn request_parses_pdf_with_optional_color_mode() {
        let json = r#"{
            "kind": {
                "format": "pdf",
                "widthMm": 210.0,
                "heightMm": 297.0,
                "title": "Pitch deck",
                "colorMode": "rgb"
            }
        }"#;
        let req: KChatArtifactRequest = serde_json::from_str(json).expect("pdf request parses");
        match req.kind {
            KChatArtifactRequestKind::Pdf(opts) => {
                assert!((opts.width_mm - 210.0).abs() < f64::EPSILON);
                assert_eq!(opts.title.as_deref(), Some("Pitch deck"));
                assert_eq!(opts.color_mode.as_deref(), Some("rgb"));
            }
            other => panic!("expected Pdf variant, got {other:?}"),
        }
    }

    #[test]
    fn brand_kit_request_parses() {
        let id = Uuid::new_v4();
        let json = format!(r#"{{ "brandKitId": "{id}", "exportPreset": "Brand Kit v3" }}"#);
        let req: KChatBrandKitArtifactRequest =
            serde_json::from_str(&json).expect("brand-kit request parses");
        assert_eq!(req.brand_kit_id, id);
        assert_eq!(req.export_preset.as_deref(), Some("Brand Kit v3"));
    }
}
