//! Compiled-in catalog of first-party demo plugins.
//!
//! KCreate is local-first and offline — there is no plugin server to
//! query. The "marketplace" instead ships a small, real catalog of
//! signed demo plugins *embedded in the binary* via [`include_bytes!`].
//! At runtime the host lists them as installable entries; choosing
//! "Install" materialises the embedded `manifest.json`,
//! `manifest.json.sig`, and `.wasm` into the on-disk plugin directory,
//! after which they behave exactly like any locally-installed plugin
//! (scanned by [`crate::registry`], verified by [`crate::trust`], run
//! by [`crate::wasm_runtime`]).
//!
//! The catalog carries genuine Ed25519 signatures produced by the
//! development signing key in
//! `demo_plugins/sign_bundled/` (regenerated by `demo_plugins/build.sh`).
//! [`bundled_trusted_keys`] exposes the public half so the host can
//! seed its trust store and render the plugins as **verified** in the
//! trust UX without the user importing any key by hand.

use crate::manifest::{ManifestError, PluginManifest, PluginSignature};
use crate::registry::SignatureStatus;
use crate::trust::{TrustError, TrustStore, TrustedKey};

/// One embedded, signed plugin: the raw manifest bytes, its signature
/// sidecar, and the WASM module — all `'static` slices baked into the
/// binary at compile time.
#[derive(Debug, Clone, Copy)]
pub struct BundledPlugin {
    /// Stable plugin id (matches `manifest.id`).
    pub id: &'static str,
    /// Verbatim bytes of `manifest.json` (the exact bytes the
    /// signature is computed over).
    pub manifest_json: &'static [u8],
    /// Verbatim bytes of `manifest.json.sig`.
    pub signature_json: &'static [u8],
    /// File name the entry-point WASM must be written as on install
    /// (matches `manifest.entry_point`).
    pub wasm_name: &'static str,
    /// The compiled WASM module bytes.
    pub wasm_bytes: &'static [u8],
}

impl BundledPlugin {
    /// Parse the embedded manifest. A failure here is a build-time
    /// packaging bug (the bytes are compiled in), surfaced as a normal
    /// [`ManifestError`] so callers can report it rather than panic.
    pub fn manifest(&self) -> Result<PluginManifest, ManifestError> {
        serde_json::from_slice(self.manifest_json).map_err(ManifestError::from)
    }

    /// Evaluate this plugin's signature against the bundled publisher
    /// key. Shipped plugins are always signed by that key, so this
    /// returns [`SignatureStatus::Verified`] in the normal case; any
    /// parse/verify failure degrades to `Invalid`/`Unsigned` rather
    /// than erroring, mirroring [`crate::registry`]'s behaviour.
    #[must_use]
    pub fn signature_status(&self) -> SignatureStatus {
        let trust = match bundled_trust_store() {
            Ok(t) => t,
            Err(_) => return SignatureStatus::Unsigned,
        };
        let sig: PluginSignature = match serde_json::from_slice(self.signature_json) {
            Ok(s) => s,
            Err(_) => return SignatureStatus::Unsigned,
        };
        match trust.verify(&sig.key_id, self.manifest_json, &sig.signature_b64) {
            Ok(()) => SignatureStatus::Verified { key_id: sig.key_id },
            Err(e) => SignatureStatus::Invalid {
                key_id: sig.key_id,
                reason: e.to_string(),
            },
        }
    }
}

/// Verbatim bytes of the bundled `trusted_keys.json`.
const TRUSTED_KEYS_JSON: &[u8] = include_bytes!("../bundled/trusted_keys.json");

const GRID_ARRANGE: BundledPlugin = BundledPlugin {
    id: "com.kcreate.demo.grid-arrange",
    manifest_json: include_bytes!("../bundled/com.kcreate.demo.grid-arrange/manifest.json"),
    signature_json: include_bytes!("../bundled/com.kcreate.demo.grid-arrange/manifest.json.sig"),
    wasm_name: "grid_arrange.wasm",
    wasm_bytes: include_bytes!("../bundled/com.kcreate.demo.grid-arrange/grid_arrange.wasm"),
};

const PALETTE_APPLY: BundledPlugin = BundledPlugin {
    id: "com.kcreate.demo.palette-apply",
    manifest_json: include_bytes!("../bundled/com.kcreate.demo.palette-apply/manifest.json"),
    signature_json: include_bytes!("../bundled/com.kcreate.demo.palette-apply/manifest.json.sig"),
    wasm_name: "palette_apply.wasm",
    wasm_bytes: include_bytes!("../bundled/com.kcreate.demo.palette-apply/palette_apply.wasm"),
};

/// The full embedded catalog. Order is stable (grid first, palette
/// second); callers that present to users sort by display name.
#[must_use]
pub fn bundled_plugins() -> &'static [BundledPlugin] {
    &[GRID_ARRANGE, PALETTE_APPLY]
}

/// Look up a single bundled plugin by id.
#[must_use]
pub fn bundled_plugin(id: &str) -> Option<&'static BundledPlugin> {
    bundled_plugins().iter().find(|p| p.id == id)
}

/// Parse the embedded publisher key list.
pub fn bundled_trusted_keys() -> Result<Vec<TrustedKey>, TrustError> {
    serde_json::from_slice(TRUSTED_KEYS_JSON).map_err(TrustError::from)
}

/// Build a [`TrustStore`] containing only the bundled publisher key(s).
/// The host merges these into its on-disk trust store so demo plugins
/// verify out of the box without the user importing a key.
pub fn bundled_trust_store() -> Result<TrustStore, TrustError> {
    TrustStore::from_keys(bundled_trusted_keys()?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_manifests_parse_and_ids_match() {
        for bp in bundled_plugins() {
            let manifest = bp.manifest().expect("bundled manifest parses");
            assert_eq!(manifest.id, bp.id, "manifest id matches catalog id");
            assert_eq!(
                manifest.entry_point, bp.wasm_name,
                "entry_point matches embedded wasm name"
            );
        }
    }

    #[test]
    fn bundled_wasm_modules_have_wasm_magic() {
        for bp in bundled_plugins() {
            assert!(
                bp.wasm_bytes.starts_with(b"\0asm"),
                "{} ships a real WASM module",
                bp.id
            );
        }
    }

    #[test]
    fn bundled_trusted_keys_parse() {
        let keys = bundled_trusted_keys().expect("trusted_keys.json parses");
        assert!(!keys.is_empty(), "at least one bundled publisher key");
        bundled_trust_store().expect("bundled trust store builds");
    }

    #[test]
    fn every_bundled_plugin_is_verified_by_bundled_key() {
        for bp in bundled_plugins() {
            match bp.signature_status() {
                SignatureStatus::Verified { key_id } => {
                    assert!(!key_id.is_empty(), "verified with a key id");
                }
                other => panic!("{} expected Verified, got {other:?}", bp.id),
            }
        }
    }
}
